eureka:
  client:
    fetch-registry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    preferIpAdress: true
server:
  port: 9011
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
